.github/workflows/ci.yaml
README.md
app-spec.yml
docker-compose.yml
scripts/smoketest.sh
src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/bct.py
src/apps/tco2_dashboard/tco2.py

Addresses a bunch of minor issues and makes it easier to run local development setup

Add docker-compose setup, fix DO name, and DRY

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/data_related_constants.py
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/helpers.py

Added bridge filter since we are showing Toucan Protocol credits only in the prototype;

added bridge filters

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/data_related_constants.py
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/helpers.py
src/apps/tco2_dashboard/tco2.py

In this PR, I have:
1) Merged Verra Registry Data
2) Used that to create Distribution of Project for TCO2s
3) Created Off-chain vs on-chain section:
4) The section includes, high level summary, comparisons based on vintage, region and project types..

Add verra data

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/tco2.py

Through this PR;
1) I have added hamburger type sidebar for smaller screens
2) Fixed width of all dbc.Cards so that they can adjust automatically to the smaller screen

added hamburger sidebar for smaller screens and fixed all widths

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/tco2.py

Trying to bring us in line with the brand guide https://drive.google.com/file/d/1cPerbGraQHOBSCcqNpdvu6LqVfZZ7DU7/view

Minor styling fixes

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/helpers.py

1) added functionality to handle missing values and added real-time dates to track metrics better
2) fixed some minor styling

Added functionality to handle missing values; added some styling fixes

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/constants.py
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/figures_carbon_pool.py
src/apps/tco2_dashboard/helpers.py
src/apps/tco2_dashboard/onchain_pool_comp.py
src/apps/tco2_dashboard/pool.py

In this PR, I have;
1. Imported KlimaRetire entity information from the subgraph
2. Used it to enable BCT and NCT retirement charts
3. Added a disclaimer saying the retired amounts only include retirements through the aggregator
resolves #38

Enable NCT and BCT retirement charts

---

.github/workflows/deploy.yaml
app-spec.yml
src/apps/tco2_dashboard/app.py

Will allow us to track how many unique visitors and page views we get

Add Plausible tracking script

---

app-spec.yml

Ugh the health check failed for some reason on this deploy

Loosen healthcheck requirements

---

src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/helpers.py
src/apps/tco2_dashboard/mco2.py
src/apps/tco2_dashboard/pool.py

In this PR, I have:
1) Added PolygonScan Column
2) Rearranged columns to bring Token Address in the front; to help users copy address easily

Add copy address feature

---

.github/workflows/deploy.yaml
app-spec.yml
src/apps/tco2_dashboard/app.py

So we properly embed into Twitter and Discord links

Add meta tags for embed

---

requirements.txt
src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/constants.py
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/helpers.py
src/apps/tco2_dashboard/homepage.py

Designs changes based off:
https://discord.com/channels/841390338324824096/967376989482786946/997220623052968086

design changes

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/constants.py
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/helpers.py
src/apps/tco2_dashboard/homepage.py
src/util.py

In this PR;
1) I have used the new Moss Retirement Subgraph that I created to get more info on MCO2 retirements beneficiary"
2) Update the top retirements chart
3) Removed whitespaces from utils
4) Fixed scrollbar color

update top retirements chart and some other quick fixes

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/homepage.py

Updated charts and fonts:
https://github.com/KlimaDAO/dash-apps/issues/63

Homepage changes based on feedback v1

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/helpers.py
src/apps/tco2_dashboard/homepage.py
src/apps/tco2_dashboard/mco2.py
src/apps/tco2_dashboard/pool.py

Works on staging, this will deploy to prod

Add social share features

---

src/apps/tco2_dashboard/app.py

Resolves https://github.com/KlimaDAO/dash-apps/issues/78

Add GTM tracking script

---

requirements.txt
src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/carbon_supply_icon.svg
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/carbon_supply.py
src/apps/tco2_dashboard/figures.py

This PR needs to be accepted **after** this condition:
- klimadao/celo-bridged-carbon must be deployed from `carbon-subgraph` project
Added Carbon Supply page:
Resolves #70

Carbon Supply charts

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/carbon_supply.py
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/onchain_pool_comp.py

In this PR;
I have added the carbon supply summary donut chart and changed the title of the carbon supply and carbon prices page.
Reference: #91

add carbon supply donut chart

---

.github/workflows/deploy.yaml
scripts/smoketest.sh
src/apps/tco2_dashboard/app.py

Switch to case-insensitive routing

---

src/apps/tco2_dashboard/app.py

This update adds names to the `CarbonOffset` entity type within the subgraph

Polygon Carbon subgraph udpate

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/assets/styles.css
src/apps/tco2_dashboard/figures.py

In this PR;
I have addressed the following issues:
https://github.com/KlimaDAO/dash-apps/issues/107
https://github.com/KlimaDAO/dash-apps/issues/106

minor supply chart and sidebar changes

---

.github/workflows/deploy.yaml
app-spec.yml

Make Gunicorn timeout configurable

---

src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_beneficiary.py
src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_chain.py
src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_pool.py
src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_token.py
src/apps/tco2_dashboard/retirement_trends/retirement_trends_factory.py
src/apps/tco2_dashboard/retirement_trends/retirement_trends_page.py
src/apps/tco2_dashboard/retirement_trends/retirement_trends_types.py

Added a beneficiary tab.
Screenshot:
Resolve #123

Beneficiary tab

---

.github/workflows/ci.yaml
.github/workflows/deploy.yaml
README.md
docker-compose.yml
requirements.txt
src/apps/tco2_dashboard/app.py
src/apps/tco2_dashboard/constants.py
src/apps/tco2_dashboard/figures.py
src/apps/tco2_dashboard/helpers.py
src/constants.py
src/util.py

This one extends #141 to all data sources (not only verra data)

140 use s3 storage for raw data

---

src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_pool.py

tooltip definitions- 'retirement' and 'redemption'

---

requirements2.txt
src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_chain.py

To make this page look cleaner: https://carbon.klimadao.finance/retirements/chain
I removed the columns with bad tiles (should we rename them instead?)

Fix retirements by chain table

---

src/apps/tco2_dashboard/helpers.py
src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_chain.py
src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_pool.py
src/apps/tco2_dashboard/retirement_trends/impl/retirement_trends_token.py

and add it to retirement trend by chain table

Factorize project link column computation logic

---

src/apps/tco2_dashboard/helpers.py

This must be merged after https://github.com/KlimaDAO/data-pipelines/pull/44/files

Integrate changes to eth subgraph

---

src/apps/tco2_dashboard/carbon_supply.py
src/apps/tco2_dashboard/figures.py

Thanks to Peter for pointing this out

Fix inconsistent naming

---

requirements2.txt
src/apps/api/app.py
src/apps/api/endpoints/__init__.py
src/apps/api/endpoints/info.py
src/apps/api/endpoints/retirements.py
src/apps/api/endpoints/tokens.py
src/apps/api/test.py
src/apps/services/cache.py
src/apps/services/metrics.py
src/apps/services/retirements.py
src/apps/services/tokens.py

- Adds token data endpoint
- Improves retirement by date and token aggregation by merging results on dates

Dash api imporvements

---

src/apps/api/endpoints/tokens.py
src/apps/services/tokens.py

See: https://github.com/KlimaDAO/klimadao/pull/2083
The token data endpoint is used to get "real time" assets prices

Use a short cache for tokens data

---

src/apps/services/s3.py
src/apps/services/tokens.py

Fixes a bug that prevented tokens price to be fetched regularly.
The call to the token price services was done as expected but it was always using the same cached version of the token dataframe.

Fixes tokens cache
